version: "3"

services:

  nginx:
    build:
      context: nginx
    container_name: nginx
    networks:
      - nodenetwork
    ports:
      - "8080:80"
    depends_on:
      - app

  app:
    build:
      context: node
    networks:
      - nodenetwork
    tty: true
    container_name: app
    volumes:
      - ./node:/usr/src/app
    entrypoint: sh -c "npm install && node index.js"
    depends_on:
      db:
       condition: service_healthy


  db:
    image: mysql:5.7
    platform: linux/amd64  # Força a execução da versão amd64
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - nodenetwork
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD" ]
      interval: 5s
      timeout: 10s
      retries: 3



networks:
  nodenetwork:
    driver: bridge
